# This builds the latest stable and prerelease versions of beammp
name: Release Pipe
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # weekly at sunday night

env:
  IMAGE_NAME: resonatortune/beammp-server
  CONTAINER_FILE: ./Containerfile

jobs:
  build-stable:
    name: Build Stable Release
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build container image (stable)
        uses: docker/build-push-action@v6
        with:
          tags: ${{ env.IMAGE_NAME }}:temp-stable
          platforms: linux/amd64
          context: .
          file: ${{ env.CONTAINER_FILE }}
          outputs: type=docker
          push: false
          build-args: |
            PRERELEASE=false

      - name: Extract version from stable image
        id: extract_stable
        run: |
          VERSION=$(docker run --rm ${{ env.IMAGE_NAME }}:temp-stable cat /beammp/version.txt)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push stable multiplatform image
        uses: docker/build-push-action@v6
        with:
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.extract_stable.outputs.version }}
            ${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64,linux/arm64
          context: .
          file: ${{ env.CONTAINER_FILE }}
          push: true
          build-args: |
            PRERELEASE=false
          labels: |
            org.opencontainers.image.version=${{ steps.extract_stable.outputs.version }}
            org.opencontainers.image.prerelease=false

  build-prerelease:
    name: Build Prerelease Version
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: prerelease
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build container image (prerelease)
        uses: docker/build-push-action@v6
        with:
          tags: ${{ env.IMAGE_NAME }}:temp-prerelease
          platforms: linux/amd64
          context: .
          file: ${{ env.CONTAINER_FILE }}
          outputs: type=docker
          push: false
          build-args: |
            PRERELEASE=true

      - name: Extract version from prerelease image
        id: extract_prerelease
        run: |
          VERSION=$(docker run --rm ${{ env.IMAGE_NAME }}:temp-prerelease cat /beammp/version.txt)
          echo "version=${VERSION}-prerelease" >> $GITHUB_OUTPUT

      - name: Build and push prerelease multiplatform image
        uses: docker/build-push-action@v6
        with:
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.extract_prerelease.outputs.version }}
            ${{ env.IMAGE_NAME }}:prerelease
          platforms: linux/amd64,linux/arm64
          context: .
          file: ${{ env.CONTAINER_FILE }}
          push: true
          build-args: |
            PRERELEASE=true
          labels: |
            org.opencontainers.image.version=${{ steps.extract_prerelease.outputs.version }}
            org.opencontainers.image.prerelease=true
