name: BeamMP Weekly Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"  # Every Sunday at midnight UTC

env:
  IMAGE_NAME: resonatortune/beammp-server
  CONTAINER_FILE: ./Containerfile

jobs:
  build-stable:
    name: Build Stable Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract stable version.txt from builder
        id: extract_stable
        run: |
          docker buildx build \
            --target=version-export \
            --build-arg PRERELEASE=false \
            --file ${{ env.CONTAINER_FILE }} \
            --output type=local,dest=build-meta-stable \
            .
          VERSION=$(cat build-meta-stable/version.txt)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push stable image
        uses: docker/build-push-action@v6
        with:
          builder: default
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.extract_stable.outputs.version }}
            ${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64
          context: .
          file: ${{ env.CONTAINER_FILE }}
          push: true
          build-args: |
            PRERELEASE=false
          labels: |
            org.opencontainers.image.version=${{ steps.extract_stable.outputs.version }}
            org.opencontainers.image.prerelease=false

  build-prerelease:
    name: Build Prerelease Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract prerelease version.txt from builder
        id: extract_prerelease
        run: |
          docker buildx build \
            --target=version-export \
            --build-arg PRERELEASE=true \
            --file ${{ env.CONTAINER_FILE }} \
            --output type=local,dest=build-meta-prerelease \
            .
          VERSION=$(cat build-meta-prerelease/version.txt)
          echo "version=${VERSION}-prerelease" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push prerelease image
        uses: docker/build-push-action@v6
        with:
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.extract_prerelease.outputs.version }}
            ${{ env.IMAGE_NAME }}:prerelease
          platforms: linux/amd64
          context: .
          file: ${{ env.CONTAINER_FILE }}
          push: true
          build-args: |
            PRERELEASE=true
          labels: |
            org.opencontainers.image.version=${{ steps.extract_prerelease.outputs.version }}
            org.opencontainers.image.prerelease=true
